[package]
name = "io_engine"
version = "0.1.0"
authors = ["YuZou <hopkings2005@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = {path = "../common" }
s3 = {path = "../s3"}
tokio = { version = "1", features = ["full"] }
crossbeam-channel = "0.4"
log = "0.4.8"