[tidb_config]
meta_store = "tidb"
tidb_info = "root:@tcp(10.5.0.17:4000)/yigfs"

[meta_service_config]
port = "9088"
log_dir = "/var/log/yigfsmeta"
log_level = "info"
tls_key_file = "/etc/yigfsmeta/serverkey.pem"
tls_cert_file = "/etc/yigfsmeta/servercert.pem"

[kafka_config]
kafka_enable = true
msg_bus_type = 1
kafka_server_list = "172.27.143.244:9092,172.27.143.245:9092,172.27.143.246:9092"